import json
import os
import re
from pathlib import Path

def generate_complete_structure(json_path="stubs.json", root="."):
    root = Path(root).resolve()

    stubs_dir   = root / "Stubs"
    core_dir    = root / "Core"
    scripts_dir = root / "Scripts"

    for d in [stubs_dir, core_dir, scripts_dir]:
        d.mkdir(parents=True, exist_ok=True)

    print("📁 Созданы папки: Stubs, Core, Scripts")

    # === Создаём GlobalUsings.cs ===
    (core_dir / "GlobalUsings.cs").write_text("""// <auto-generated/>
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
""", encoding="utf-8")
    print("✅ Создан GlobalUsings.cs")

    # === Создаём .csproj файлы ===
    (core_dir / "Core.csproj").write_text("""<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\\Stubs\\**\\*.cs" />
    <Compile Include="..\\common\\**\\*.cs" />
  </ItemGroup>
</Project>""", encoding="utf-8")
    print("✅ Создан Core/Core.csproj")

    (scripts_dir / "Scripts.csproj").write_text("""<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\\script_links\\**\\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\\Core\\Core.csproj" />
  </ItemGroup>
</Project>""", encoding="utf-8")
    print("✅ Создан Scripts/Scripts.csproj")

    # === Читаем JSON ===
    with open(json_path, 'r', encoding='utf-8') as f:
        lines = json.load(f)

    # === Парсим стабы (ИСПРАВЛЕНО) ===
    stubs = parse_stubs_with_namespace(lines)

    # === Сохраняем стабы ===
    created = 0
    for full_name, code in stubs.items():
        if not code.strip():
            continue

        # Разбиваем на папки по namespace
        parts = full_name.split('.')
        if len(parts) > 1:
            folder = stubs_dir / Path(*parts[:-1])
            filename = parts[-1] + ".cs"
        else:
            folder = stubs_dir
            filename = full_name + ".cs"

        folder.mkdir(parents=True, exist_ok=True)
        file_path = folder / filename

        # Добавляем using'и, если нужно
        final_code = ensure_usings(code)

        file_path.write_text(final_code, encoding="utf-8")
        created += 1
        print(f"  → {file_path.relative_to(root)}")

    print(f"\n✅ Готово! Создано файлов стабов: {created}")
    print("\nТеперь выполни:")
    print("dotnet new sln -n Dev")
    print("dotnet sln Dev.sln add Core/Core.csproj Scripts/Scripts.csproj")


def parse_stubs_with_namespace(lines):
    """Парсер, который сохраняет namespace"""
    stubs = {}
    current_namespace = ""
    current_type_name = ""
    current_code = []
    brace_count = 0
    in_type = False

    namespace_pattern = re.compile(r'^\s*namespace\s+([A-Za-z0-9_.]+)\s*;')
    type_pattern = re.compile(
        r'^\s*public\s+(?:abstract\s+|sealed\s+|static\s+)?(class|interface|enum|struct|record)\s+([A-Za-z_][A-Za-z0-9_]*)'
    )

    for line in lines:
        stripped = line.strip()

        # Ловим namespace
        ns_match = namespace_pattern.match(stripped)
        if ns_match:
            current_namespace = ns_match.group(1)
            continue

        # Начало типа
        type_match = type_pattern.match(stripped)
        if type_match and not in_type:
            current_type_name = type_match.group(2)
            current_code = []

            # === ГЛАВНОЕ ИСПРАВЛЕНИЕ: добавляем namespace в начало кода ===
            if current_namespace:
                current_code.append(f"namespace {current_namespace};")
                current_code.append("")

            current_code.append(line)
            brace_count = line.count('{') - line.count('}')
            in_type = True
            continue

        if in_type:
            current_code.append(line)
            brace_count += line.count('{') - line.count('}')

            if brace_count <= 0:
                full_name = f"{current_namespace}.{current_type_name}" if current_namespace else current_type_name
                stubs[full_name] = '\n'.join(current_code)
                in_type = False
                current_code = []
                current_type_name = ""
                brace_count = 0

    return stubs


def ensure_usings(code: str) -> str:
    """Добавляет using'и, если их нет"""
    needed = [
        "using System;",
        "using System.Collections.Generic;",
        "using System.Linq;",
    ]
    if any(u in code for u in needed):
        return code

    usings = "\n".join(needed) + "\n\n"
    return usings + code


if __name__ == "__main__":
    generate_complete_structure(json_path="stubs.json", root=".")