import json
import re
from pathlib import Path

def generate_complete_structure(json_path="stubs.json", root="."):
    root = Path(root).resolve()

    stubs_dir = root / "Stubs"
    core_dir = root / "Core"
    scripts_dir = root / "Scripts"

    for folder in [stubs_dir, core_dir, scripts_dir]:
        folder.mkdir(parents=True, exist_ok=True)

    print("📁 Созданы папки")

    # === Создаём проекты ===
    (core_dir / "GlobalUsings.cs").write_text("""// <auto-generated/>
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
""", encoding="utf-8")

    (core_dir / "Core.csproj").write_text("""<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\\Stubs\\**\\*.cs" />
    <Compile Include="..\\common\\**\\*.cs" />
  </ItemGroup>
</Project>""", encoding="utf-8")

    (scripts_dir / "Scripts.csproj").write_text("""<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\\script_links\\**\\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\\Core\\Core.csproj" />
  </ItemGroup>
</Project>""", encoding="utf-8")

    print("✅ Созданы проекты Core и Scripts")

    with open(json_path, 'r', encoding='utf-8') as f:
        lines = json.load(f)

    stubs = parse_stubs(lines)

    created = 0
    for full_name, code in stubs.items():
        if not code.strip():
            continue

        parts = full_name.split('.')
        if len(parts) > 1:
            folder = stubs_dir / Path(*parts[:-1])
            filename = parts[-1] + ".cs"
        else:
            folder = stubs_dir
            filename = full_name + ".cs"

        folder.mkdir(parents=True, exist_ok=True)
        (folder / filename).write_text(code, encoding="utf-8")
        created += 1
        print(f"  → {folder.relative_to(root) / filename}")

    print(f"\n✅ Готово! Создано файлов: {created}")


def parse_stubs(lines):
    """Улучшенный парсер, который сохраняет using и namespace"""
    stubs = {}
    current_namespace = ""
    current_type_name = ""
    current_code = []
    brace_count = 0
    in_type = False

    namespace_pattern = re.compile(r'^\s*namespace\s+([A-Za-z0-9_.]+)\s*;')
    type_pattern = re.compile(
        r'^\s*public\s+(?:abstract\s+|sealed\s+|static\s+)?(class|interface|enum|struct|record)\s+([A-Za-z_][A-Za-z0-9_]*)'
    )

    for line in lines:
        stripped = line.strip()

        # Пропускаем комментарии и пустые строки в начале
        if not stripped or stripped.startswith("//"):
            if not in_type:
                continue

        # Ловим namespace
        ns_match = namespace_pattern.match(stripped)
        if ns_match and not in_type:
            current_namespace = ns_match.group(1)
            continue

        # Начало типа
        type_match = type_pattern.match(stripped)
        if type_match and not in_type:
            current_type_name = type_match.group(2)
            current_code = [line]
            brace_count = line.count('{') - line.count('}')
            in_type = True
            continue

        if in_type:
            current_code.append(line)
            brace_count += line.count('{') - line.count('}')

            if brace_count <= 0:
                full_name = f"{current_namespace}.{current_type_name}" if current_namespace else current_type_name
                stubs[full_name] = '\n'.join(current_code)
                in_type = False
                current_code = []
                current_type_name = ""
                brace_count = 0

    return stubs


if __name__ == "__main__":
    generate_complete_structure(json_path="stubs.json", root=".")