import json
import re
from pathlib import Path


def generate_complete_structure(json_path="stubs.json", root="."):
    root = Path(root).resolve()

    # === Создаём структуру папок ===
    stubs_dir = root / "Stubs"
    core_dir = root / "Core"
    scripts_dir = root / "Scripts"
    common_dir = root / "common"
    script_links_dir = root / "script_links"

    for d in [stubs_dir, core_dir, scripts_dir]:
        d.mkdir(parents=True, exist_ok=True)

    print("📁 Созданы папки: Stubs, Core, Scripts")

    # === 1. Создаём GlobalUsings.cs ===
    global_usings = core_dir / "GlobalUsings.cs"
    global_usings.write_text(
        """// <auto-generated/>
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
""",
        encoding="utf-8",
    )
    print("✅ Создан GlobalUsings.cs")

    # === 2. Создаём Core.csproj ===
    core_csproj = core_dir / "Core.csproj"
    core_csproj.write_text(
        """<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\\Stubs\\**\\*.cs" />
    <Compile Include="..\\common\\**\\*.cs" />
  </ItemGroup>
</Project>""",
        encoding="utf-8",
    )
    print("✅ Создан Core/Core.csproj")

    # === 3. Создаём Scripts.csproj ===
    scripts_csproj = scripts_dir / "Scripts.csproj"
    scripts_csproj.write_text(
        """<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\\script_links\\**\\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\\Core\\Core.csproj" />
  </ItemGroup>
</Project>""",
        encoding="utf-8",
    )
    print("✅ Создан Scripts/Scripts.csproj")

    # === 4. Читаем JSON и парсим стабы ===
    with open(json_path, "r", encoding="utf-8") as f:
        lines = json.load(f)

    stubs = parse_stubs(lines)

    # === 5. Сохраняем стабы в Stubs/ ===
    created_files = 0
    for full_name, code in stubs.items():
        if not code.strip():
            continue

        # Создаём подпапки по namespace
        parts = full_name.split(".")
        if len(parts) > 1:
            namespace_path = Path(*parts[:-1])
            file_name = parts[-1] + ".cs"
            target_dir = stubs_dir / namespace_path
        else:
            target_dir = stubs_dir
            file_name = full_name + ".cs"

        target_dir.mkdir(parents=True, exist_ok=True)
        file_path = target_dir / file_name

        # Добавляем using'и, если их нет
        final_code = add_usings_if_needed(code)

        file_path.write_text(final_code, encoding="utf-8")
        created_files += 1
        print(f"  → {file_path.relative_to(root)}")

    print(f"\n✅ Создано файлов стабов: {created_files}")
    print("🎉 Структура полностью готова!")
    print("\nТеперь открой в VS Code папку и создай решение:")
    print("dotnet new sln -n Dev")
    print("dotnet sln Dev.sln add Core/Core.csproj")
    print("dotnet sln Dev.sln add Scripts/Scripts.csproj")


def parse_stubs(lines):
    """Умный парсер с подсчётом баланса скобок"""
    stubs = {}
    current_namespace = ""
    current_type = ""
    current_code = []
    brace_count = 0
    in_type = False

    type_start_pattern = re.compile(
        r"^\s*public\s+(?:abstract\s+|sealed\s+|static\s+)?(class|interface|enum|struct|record)\s+([A-Za-z_][A-Za-z0-9_]*)"
    )
    namespace_pattern = re.compile(r"^\s*namespace\s+([A-Za-z0-9_.]+)\s*;")

    for line in lines:
        stripped = line.strip()

        # Namespace
        ns_match = namespace_pattern.match(stripped)
        if ns_match:
            current_namespace = ns_match.group(1)
            continue

        # Начало типа
        type_match = type_start_pattern.match(stripped)
        if type_match and not in_type:
            current_type = type_match.group(2)
            current_code = [line]
            brace_count = line.count("{") - line.count("}")
            in_type = True
            continue

        if in_type:
            current_code.append(line)
            brace_count += line.count("{") - line.count("}")

            # Конец типа
            if brace_count <= 0:
                full_name = (
                    f"{current_namespace}.{current_type}"
                    if current_namespace
                    else current_type
                )
                stubs[full_name] = "\n".join(current_code)
                in_type = False
                current_code = []
                current_type = ""
                brace_count = 0

    return stubs


def add_usings_if_needed(code: str) -> str:
    """Добавляет using'и, если их ещё нет"""
    needed_usings = [
        "using System;",
        "using System.Collections.Generic;",
        "using System.Linq;",
    ]

    has_using = any(u in code for u in needed_usings)
    if has_using:
        return code

    # Добавляем using'и в начало
    usings_block = "\n".join(needed_usings) + "\n\n"
    return usings_block + code


if __name__ == "__main__":
    generate_complete_structure(json_path="stubs.json", root=".")
